alter table public.contact_submissions add column submission_number bigint generated by default as identity;
alter table public.ride_requests add column submission_number bigint generated by default as identity;
alter table public.partner_requests add column submission_number bigint generated by default as identity;
alter table public.driver_applications add column submission_number bigint generated by default as identity;

alter table public.contact_submissions add constraint contact_submissions_submission_number_key unique (submission_number);
alter table public.ride_requests add constraint ride_requests_submission_number_key unique (submission_number);
alter table public.partner_requests add constraint partner_requests_submission_number_key unique (submission_number);
alter table public.driver_applications add constraint driver_applications_submission_number_key unique (submission_number);

grant update (status) on table public.contact_submissions, public.ride_requests, public.partner_requests, public.driver_applications to authenticated;

create policy "Admins can update contact submissions"
on public.contact_submissions for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can update ride requests"
on public.ride_requests for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can update partner requests"
on public.partner_requests for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

create policy "Admins can update driver applications"
on public.driver_applications for update to authenticated
using ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
with check ((select auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');
